/* eslint-disable perfectionist/sort-objects */
const languages = {
  aa: 'Afaraf',
  ab: 'аҧсуа бызшәа',
  ae: 'Avesta',
  af: 'Afrikaans',
  ak: 'Akan',
  am: 'አማርኛ',
  an: 'aragonés',
  ar: 'العربية',
  as: 'অসমীয়া',
  av: 'авар мацӀ',
  ay: 'Aymar aru',
  az: 'azərbaycan dili',
  ba: 'башҡорт теле',
  be: 'беларуская мова',
  bg: 'български език',
  bh: 'भोजपुरी',
  bi: 'Bislama',
  bm: 'Bamanankan',
  bn: 'বাংলা',
  bo: 'བོད་སྐད་',
  br: 'brezhoneg',
  bs: 'bosanski jezik',
  ca: 'català',
  ce: 'нохчийн мотт',
  ch: 'Chamoru',
  co: 'corsu',
  cr: 'ᓀᐦᐃᔭᐍᐏᐣ',
  cs: 'čeština',
  cu: 'ѩзыкъ словѣньскъ',
  cv: 'чӑваш чӗлхи',
  cy: 'Cymraeg',
  da: 'dansk',
  de: 'Deutsch',
  dv: 'ދިވެހި',
  dz: 'རྫོང་ཁ',
  ee: 'Eʋegbe',
  el: 'ελληνικά',
  en: 'English',
  eo: 'Esperanto',
  es: 'español',
  et: 'eesti',
  eu: 'euskara',
  fa: 'فارسی',
  ff: 'Fulfulde',
  fi: 'suomi',
  fj: 'vosa Vakaviti',
  fo: 'Føroyskt',
  fr: 'français',
  fy: 'Frysk',
  ga: 'Gaeilge',
  gd: 'Gàidhlig',
  gl: 'galego',
  gn: "Avañe'ẽ",
  gu: 'ગુજરાતી',
  gv: 'Gaelg',
  ha: 'Hausa',
  he: 'עברית',
  hi: 'हिन्दी',
  ho: 'Hiri Motu',
  hr: 'hrvatski jezik',
  ht: 'Kreyòl ayisyen',
  hu: 'magyar',
  hy: 'Հայերեն',
  hz: 'Otjiherero',
  ia: 'Interlingua',
  id: 'Bahasa Indonesia',
  ie: 'Interlingue',
  ig: 'Asụsụ Igbo',
  ii: 'ꆈꌠ꒿ Nuosuhxop',
  ik: 'Iñupiaq',
  io: 'Ido',
  is: 'Íslenska',
  it: 'italiano',
  iu: 'ᐃᓄᒃᑎᑐᑦ',
  ja: '日本語',
  jv: 'basa Jawa',
  ka: 'ქართული',
  kg: 'Kikongo',
  ki: 'Gĩkũyũ',
  kj: 'Kuanyama',
  kk: 'қазақ тілі',
  kl: 'Kalaallisut',
  km: 'ខ្មែរ',
  kn: 'ಕನ್ನಡ',
  ko: '한국어',
  kr: 'Kanuri',
  ks: 'कश्मीरी',
  ku: 'Kurdî',
  kv: 'коми кыв',
  kw: 'Kernewek',
  ky: 'Кыргызча',
  la: 'lingua Latina',
  lb: 'Lëtzebuergesch',
  lg: 'Luganda',
  li: 'Limburgs',
  ln: 'Lingála',
  lo: 'ພາສາລາວ',
  lt: 'lietuvių kalba',
  lu: 'Kiluba',
  lv: 'latviešu valoda',
  mg: 'fiteny malagasy',
  mh: 'Kajin M̧ajeļ',
  mi: 'te reo Māori',
  mk: 'македонски јазик',
  ml: 'മലയാളം',
  mn: 'монгол',
  mr: 'मराठी',
  ms: 'bahasa Melayu',
  mt: 'Malti',
  my: 'ဗမာစာ',
  na: 'Ekakairũ Naoero',
  nb: 'Norsk bokmål',
  nd: 'isiNdebele',
  ne: 'नेपाली',
  ng: 'Owambo',
  nl: 'Nederlands',
  nn: 'Norsk nynorsk',
  no: 'Norsk',
  nr: 'isiNdebele',
  nv: 'Diné bizaad',
  ny: 'chiCheŵa',
  oc: 'occitan',
  oj: 'ᐊᓂᔑᓈᐯᒧᐎᓐ',
  om: 'Afaan Oromoo',
  or: 'ଓଡ଼ିଆ',
  os: 'ирон æвзаг',
  pa: 'ਪੰਜਾਬੀ',
  pi: 'पालि',
  pl: 'polski',
  ps: 'پښتو',
  pt: 'português',
  qu: 'Runa Simi',
  rm: 'Rumantsch Grischun',
  rn: 'Ikirundi',
  ro: 'română',
  ru: 'русский язык',
  rw: 'Ikinyarwanda',
  sa: 'संस्कृतम्',
  sc: 'Sardu',
  sd: 'سنڌي',
  se: 'Davvisámegiella',
  sg: 'yângâ tî sängö',
  si: 'සිංහල',
  sk: 'slovenčina',
  sl: 'slovenščina',
  sm: "gagana fa'a Samoa",
  sn: 'chiShona',
  so: 'Soomaaliga',
  sq: 'Shqip',
  sr: 'српски језик',
  ss: 'SiSwati',
  st: 'Sesotho',
  su: 'Basa Sunda',
  sv: 'svenska',
  sw: 'Kiswahili',
  ta: 'தமிழ்',
  te: 'తెలుగు',
  tg: 'тоҷикӣ',
  th: 'ไทย',
  ti: 'ትግርኛ',
  tk: 'Türkmen',
  tl: 'Wikang Tagalog',
  tn: 'Setswana',
  to: 'lea faka-Tonga',
  tr: 'Türkçe',
  ts: 'Xitsonga',
  tt: 'татар теле',
  tw: 'Twi',
  ty: 'Reo Tahiti',
  ug: 'ئۇيغۇرچە',
  uk: 'українська мова',
  ur: 'اردو',
  uz: 'Oʻzbek',
  ve: 'Tshivenḓa',
  vi: 'Tiếng Việt',
  vo: 'Volapük',
  wa: 'Walon',
  wo: 'Wolof',
  xh: 'isiXhosa',
  yi: 'ייִדיש',
  yo: 'Yorùbá',
  za: 'Saɯ cueŋƅ',
  zh: '中文',
  zu: 'isiZulu',
};

const rtlLanguages = new Set(['ar', 'dv', 'fa', 'he', 'ps', 'sd', 'ug', 'ur', 'yi']);

export type LangCode = keyof typeof languages;

/**
 * Return writing direction based on ISO-639-1 language code.
 *
 * Strictly speaking, direction is dictated by script, not language, and languages can have multiple scripts.
 * Examples are Sindhi, which can be written in both Perso-Arabic (rtl) and Devanagari (ltr), and Hausa, which can be
 * written in both Boko (ltr) and Arabic.
 * A possible solution for this would be to expand this component to also incorporate the ISO 15924 standard for script
 * subtags on language codes.
 *
 * @param lang two-letter language code as defined in ISO-639-1
 * @returns `"rtl"` or `"ltr"`
 */
export const direction = (lang: string): 'rtl' | 'ltr' => {
  return rtlLanguages.has(lang) ? 'rtl' : 'ltr';
};

export default languages;
