import { TokenCollection } from './types';

export const tokenCollection: TokenCollection = [
  {
    name: 'basis.color.default',
    tokens: [
      {
        $extensions: {
          'nl.nldesignsystem.color-scale-position': 1,
          'nl.nldesignsystem.path': 'basis.color.default.bg-document',
          'nl.nldesignsystem.reference-count': 13,
          'nl.nldesignsystem.referenced-at': [
            'basis.form-control.background-color',
            'utrecht.calendar.background-color',
            'utrecht.drawer.background-color',
            'utrecht.document.background-color',
            'utrecht.page-body.background-color',
            'utrecht.page-body.content.background-color',
            'utrecht.root.background-color',
            'utrecht.body.background-color',
            'utrecht.page-header.background-color',
            'todo.drawer.background-color',
            'todo.progress-list.step-marker.not-checked.background-color',
            'ams.dialog.background-color',
            'denhaag.process-steps.step-marker.background-color',
          ],
          'nl.nldesignsystem.token-subtype': 'background-color',
        },
        $type: 'color',
        $value: {
          alpha: 1,
          colorSpace: 'srgb',
          components: [0.9882352941176471, 0.9882352941176471, 0.9882352941176471],
        },
      },
      {
        $extensions: {
          'nl.nldesignsystem.color-scale-position': 2,
          'nl.nldesignsystem.path': 'basis.color.default.bg-subtle',
          'nl.nldesignsystem.reference-count': 4,
          'nl.nldesignsystem.referenced-at': [
            'basis.form-control.read-only.accent-color',
            'basis.form-control.read-only.background-color',
            'utrecht.nav-bar.background-color',
            'utrecht.nav-bar.content.background-color',
          ],
          'nl.nldesignsystem.token-subtype': 'background-color',
        },
        $type: 'color',
        $value: {
          alpha: 1,
          colorSpace: 'srgb',
          components: [0.9647058823529412, 0.9647058823529412, 0.9647058823529412],
        },
      },
      {
        $extensions: {
          'nl.nldesignsystem.color-scale-position': 3,
          'nl.nldesignsystem.path': 'basis.color.default.bg-default',
          'nl.nldesignsystem.reference-count': 18,
          'nl.nldesignsystem.referenced-at': [
            'basis.color.disabled.bg-default',
            'utrecht.accordion.button.background-color',
            'utrecht.code.background-color',
            'utrecht.code-block.background-color',
            'utrecht.data-badge.background-color',
            'utrecht.spotlight-section.background-color',
            'utrecht.number-badge.background-color',
            'utrecht.status-badge.background-color',
            'utrecht.status-badge.inactive.background-color',
            'utrecht.form-toggle.thumb.background-color',
            'todo.case-card.archived.background-color',
            'todo.status-badge.background-color',
            'nl.button.default.background-color',
            'nl.code.background-color',
            'nl.code-block.background-color',
            'nl.data-badge.background-color',
            'nl.number-badge.background-color',
            'denhaag.file.left.background-color',
          ],
          'nl.nldesignsystem.token-subtype': 'background-color',
        },
        $type: 'color',
        $value: {
          alpha: 1,
          colorSpace: 'srgb',
          components: [0.9450980392156862, 0.9450980392156862, 0.9450980392156862],
        },
      },
      {
        $extensions: {
          'nl.nldesignsystem.color-scale-position': 4,
          'nl.nldesignsystem.path': 'basis.color.default.bg-hover',
          'nl.nldesignsystem.reference-count': 10,
          'nl.nldesignsystem.referenced-at': [
            'basis.form-control.hover.background-color',
            'utrecht.accordion.button.hover.background-color',
            'utrecht.button.hover.background-color',
            'utrecht.pagination.page-link.hover.background-color',
            'utrecht.pagination.relative-link.hover.background-color',
            'todo.case-card.archived.hover.background-color',
            'nl.button.default.hover.background-color',
            'denhaag.action.single.hover.background-color',
            'rhc.navigation-list.item.hover.background-color',
            'lux.login-link.hover.background-color',
          ],
          'nl.nldesignsystem.token-subtype': 'background-color',
        },
        $type: 'color',
        $value: {
          alpha: 1,
          colorSpace: 'srgb',
          components: [0.9215686274509803, 0.9215686274509803, 0.9215686274509803],
        },
      },
      {
        $extensions: {
          'nl.nldesignsystem.color-scale-position': 5,
          'nl.nldesignsystem.path': 'basis.color.default.bg-active',
          'nl.nldesignsystem.reference-count': 13,
          'nl.nldesignsystem.referenced-at': [
            'basis.form-control.active.background-color',
            'utrecht.accordion.button.active.background-color',
            'utrecht.button.active.background-color',
            'utrecht.button.pressed.background-color',
            'utrecht.pagination.page-link.current.background-color',
            'todo.case-card.archived.active.background-color',
            'todo.case-card.archived.decoration.folder.background-color',
            'todo.case-card.archived.decoration.folder.active.background-color',
            'todo.case-card.archived.decoration.folder.hover.background-color',
            'todo.pagination.page-link.current.background-color',
            'nl.button.default.active.background-color',
            'rhc.navigation-list.item.active.background-color',
            'lux.login-link.active.background-color',
          ],
          'nl.nldesignsystem.token-subtype': 'background-color',
        },
        $type: 'color',
        $value: {
          alpha: 1,
          colorSpace: 'srgb',
          components: [0.8980392156862745, 0.8980392156862745, 0.8980392156862745],
        },
      },
      {
        $extensions: {
          'nl.nldesignsystem.color-scale-position': 6,
          'nl.nldesignsystem.path': 'basis.color.default.border-subtle',
          'nl.nldesignsystem.reference-count': 18,
          'nl.nldesignsystem.referenced-at': [
            'basis.color.disabled.border-subtle',
            'utrecht.accordion.section.border-color',
            'utrecht.accordion.section.hover.border-color',
            'utrecht.drawer.border-color',
            'utrecht.table.header.border-block-end-color',
            'utrecht.table.row.border-block-end-color',
            'todo.drawer.border-color',
            'todo.drawer.header.border-color',
            'todo.drawer.footer.border-color',
            'todo.form-summary.item.border-color',
            'todo.table.footer.border-block-start-color',
            'ams.dialog.border-color',
            'denhaag.description-list.border-color',
            'denhaag.file.border-color',
            'denhaag.side-navigation.expand-separator.color',
            'denhaag.tabs.border-color',
            'denhaag.action.border-color',
            'rhc.navigation-list.item.border-color',
          ],
          'nl.nldesignsystem.token-subtype': 'border-color',
        },
        $type: 'color',
        $value: {
          alpha: 1,
          colorSpace: 'srgb',
          components: [0.7686274509803922, 0.7686274509803922, 0.7686274509803922],
        },
      },
      {
        $extensions: {
          'nl.nldesignsystem.color-scale-position': 7,
          'nl.nldesignsystem.path': 'basis.color.default.border-default',
          'nl.nldesignsystem.reference-count': 13,
          'nl.nldesignsystem.referenced-at': [
            'basis.form-control.border-color',
            'utrecht.button.border-color',
            'utrecht.spotlight-section.border-color',
            'utrecht.separator.color',
            'todo.progress-list.connector.not-checked.border-color',
            'todo.progress-list.step-marker.not-checked.border-color',
            'nl.button.default.border-color',
            'denhaag.process-steps.step-line.color',
            'denhaag.process-steps.step-marker.border-color',
            'denhaag.process-steps.sub-step-marker.border-color',
            'denhaag.process-steps.sub-step-marker.current.border-color',
            'denhaag.step-marker.connector.default.outline-color',
            'lux.login-link.border-color',
          ],
          'nl.nldesignsystem.token-subtype': 'border-color',
        },
        $type: 'color',
        $value: {
          alpha: 1,
          colorSpace: 'srgb',
          components: [0.5254901960784314, 0.5254901960784314, 0.5254901960784314],
        },
      },
      {
        $extensions: {
          'nl.nldesignsystem.color-scale-position': 8,
          'nl.nldesignsystem.path': 'basis.color.default.border-hover',
          'nl.nldesignsystem.reference-count': 4,
          'nl.nldesignsystem.referenced-at': [
            'basis.form-control.hover.border-color',
            'utrecht.button.hover.border-color',
            'nl.button.default.hover.border-color',
            'lux.login-link.hover.border-color',
          ],
          'nl.nldesignsystem.token-subtype': 'border-color',
        },
        $type: 'color',
        $value: {
          alpha: 1,
          colorSpace: 'srgb',
          components: [0.48627450980392156, 0.48627450980392156, 0.48627450980392156],
        },
      },
      {
        $extensions: {
          'nl.nldesignsystem.color-scale-position': 9,
          'nl.nldesignsystem.path': 'basis.color.default.border-active',
          'nl.nldesignsystem.reference-count': 7,
          'nl.nldesignsystem.referenced-at': [
            'basis.form-control.active.border-color',
            'basis.form-control.focus.border-color',
            'utrecht.button.active.border-color',
            'utrecht.button.pressed.border-color',
            'nl.button.default.active.border-color',
            'denhaag.tabs.tab-indicator.border-color',
            'lux.login-link.active.border-color',
          ],
          'nl.nldesignsystem.token-subtype': 'border-color',
        },
        $type: 'color',
        $value: {
          alpha: 1,
          colorSpace: 'srgb',
          components: [0.4470588235294118, 0.4470588235294118, 0.4470588235294118],
        },
      },
      {
        $extensions: {
          'nl.nldesignsystem.color-scale-position': 10,
          'nl.nldesignsystem.path': 'basis.color.default.color-subtle',
          'nl.nldesignsystem.reference-count': 15,
          'nl.nldesignsystem.referenced-at': [
            'basis.color.disabled.color-subtle',
            'basis.color.disabled.color-default',
            'basis.color.disabled.color-hover',
            'basis.color.disabled.color-active',
            'basis.color.disabled.color-document',
            'basis.form-control.placeholder.color',
            'utrecht.blockquote.attribution.color',
            'utrecht.breadcrumb-nav.separator.color',
            'utrecht.form-field-description.color',
            'todo.breadcrumb-nav.separator.color',
            'todo.pagination.ellipses.color',
            'todo.progress-list.step-heading.not-checked.color',
            'denhaag.process-steps.step-description.color',
            'denhaag.process-steps.step-metaddata.color',
            'rhc.navigation-list.item.description.color',
          ],
          'nl.nldesignsystem.token-subtype': 'color',
        },
        $type: 'color',
        $value: {
          alpha: 1,
          colorSpace: 'srgb',
          components: [0.38823529411764707, 0.38823529411764707, 0.38823529411764707],
        },
      },
      {
        $extensions: {
          'nl.nldesignsystem.color-scale-position': 11,
          'nl.nldesignsystem.path': 'basis.color.default.color-default',
          'nl.nldesignsystem.reference-count': 9,
          'nl.nldesignsystem.referenced-at': [
            'utrecht.button.color',
            'utrecht.data-badge.color',
            'utrecht.number-badge.color',
            'utrecht.status-badge.color',
            'utrecht.status-badge.inactive.color',
            'todo.status-badge.color',
            'nl.button.default.color',
            'nl.data-badge.color',
            'nl.number-badge.color',
          ],
          'nl.nldesignsystem.token-subtype': 'color',
        },
        $type: 'color',
        $value: {
          alpha: 1,
          colorSpace: 'srgb',
          components: [0.34901960784313724, 0.34901960784313724, 0.34901960784313724],
        },
      },
      {
        $extensions: {
          'nl.nldesignsystem.color-scale-position': 12,
          'nl.nldesignsystem.path': 'basis.color.default.color-hover',
          'nl.nldesignsystem.reference-count': 0,
          'nl.nldesignsystem.referenced-at': [],
          'nl.nldesignsystem.token-subtype': 'color',
        },
        $type: 'color',
        $value: {
          alpha: 1,
          colorSpace: 'srgb',
          components: [0.29411764705882354, 0.29411764705882354, 0.29411764705882354],
        },
      },
      {
        $extensions: {
          'nl.nldesignsystem.color-scale-position': 13,
          'nl.nldesignsystem.path': 'basis.color.default.color-active',
          'nl.nldesignsystem.reference-count': 3,
          'nl.nldesignsystem.referenced-at': [
            'utrecht.button.active.color',
            'utrecht.button.pressed.color',
            'nl.button.default.active.color',
          ],
          'nl.nldesignsystem.token-subtype': 'color',
        },
        $type: 'color',
        $value: {
          alpha: 1,
          colorSpace: 'srgb',
          components: [0.24313725490196078, 0.24313725490196078, 0.24313725490196078],
        },
      },
      {
        $extensions: {
          'nl.nldesignsystem.color-scale-position': 14,
          'nl.nldesignsystem.path': 'basis.color.default.color-document',
          'nl.nldesignsystem.reference-count': 67,
          'nl.nldesignsystem.referenced-at': [
            'basis.form-control.color',
            'basis.form-control.read-only.color',
            'basis.heading.color',
            'utrecht.blockquote.color',
            'utrecht.blockquote.content.color',
            'utrecht.calendar.navigation.label.color',
            'utrecht.code.color',
            'utrecht.code-block.color',
            'utrecht.drawer.color',
            'utrecht.document.color',
            'utrecht.form-fieldset.legend.color',
            'utrecht.form-fieldset.section.color',
            'utrecht.figure.caption.color',
            'utrecht.form-label.color',
            'utrecht.form-label.checkbox.color',
            'utrecht.form-label.radio.color',
            'utrecht.nav-bar.color',
            'utrecht.nav-bar.content.color',
            'utrecht.spotlight-section.color',
            'utrecht.page-body.color',
            'utrecht.page-body.content.color',
            'utrecht.pagination.page-link.current.color',
            'utrecht.paragraph.color',
            'utrecht.paragraph.lead.color',
            'utrecht.paragraph.small.color',
            'utrecht.pre-heading.color',
            'utrecht.root.color',
            'utrecht.table.caption.color',
            'utrecht.table.footer.color',
            'utrecht.table.header.color',
            'utrecht.unordered-list.marker.color',
            'utrecht.body.color',
            'utrecht.page-header.color',
            'utrecht.page-footer.color',
            'todo.case-card.color',
            'todo.case-card.description.color',
            'todo.case-card.metadata.color',
            'todo.case-card.archived.color',
            'todo.case-card.archived.description.color',
            'todo.case-card.archived.metadata.color',
            'todo.drawer.color',
            'todo.drawer.header.label.color',
            'todo.form-field-label-suffix.color',
            'todo.form-summary.item.color',
            'todo.pagination.description.color',
            'todo.pagination.page-link.current.color',
            'todo.progress-list.button.icon.current.color',
            'todo.progress-list.step-heading.current.color',
            'todo.task-list.color',
            'ams.description-list.color',
            'ams.figure.caption.color',
            'nl.code.color',
            'nl.code-block.color',
            'nl.paragraph.color',
            'denhaag.contact-timeline.step-meta.marker.color',
            'denhaag.description-list.color',
            'denhaag.description-list.title.color',
            'denhaag.process-steps.step-heading.color',
            'denhaag.process-steps.step-heading.checked.color',
            'denhaag.process-steps.step-heading.current.color',
            'denhaag.process-steps.step-heading.warning.color',
            'denhaag.process-steps.step-marker.color',
            'denhaag.process-steps.sub-step-heading.color',
            'denhaag.step-marker.default.nested.color',
            'denhaag.tabs.tab.selected.color',
            'denhaag.action.color',
            'denhaag.action.date.color',
          ],
          'nl.nldesignsystem.token-subtype': 'color',
        },
        $type: 'color',
        $value: {
          alpha: 1,
          colorSpace: 'srgb',
          components: [0.10588235294117647, 0.10588235294117647, 0.10588235294117647],
        },
      },
    ],
  },
  {
    name: 'basis.color.accent-1',
    tokens: [
      {
        $extensions: {
          'nl.nldesignsystem.color-scale-position': 1,
          'nl.nldesignsystem.path': 'basis.color.accent-1.bg-document',
          'nl.nldesignsystem.reference-count': 5,
          'nl.nldesignsystem.referenced-at': [
            'basis.color.accent-2.bg-document',
            'basis.color.accent-3.bg-document',
            'basis.color.action-1.bg-document',
            'basis.color.action-2.bg-document',
            'basis.color.selected.bg-document',
          ],
          'nl.nldesignsystem.token-subtype': 'background-color',
        },
        $type: 'color',
        $value: {
          alpha: 1,
          colorSpace: 'srgb',
          components: [0.984313725490196, 0.9882352941176471, 0.9921568627450981],
        },
      },
      {
        $extensions: {
          'nl.nldesignsystem.color-scale-position': 2,
          'nl.nldesignsystem.path': 'basis.color.accent-1.bg-subtle',
          'nl.nldesignsystem.reference-count': 5,
          'nl.nldesignsystem.referenced-at': [
            'basis.color.accent-2.bg-subtle',
            'basis.color.accent-3.bg-subtle',
            'basis.color.action-1.bg-subtle',
            'basis.color.action-2.bg-subtle',
            'basis.color.selected.bg-subtle',
          ],
          'nl.nldesignsystem.token-subtype': 'background-color',
        },
        $type: 'color',
        $value: {
          alpha: 1,
          colorSpace: 'srgb',
          components: [0.9568627450980393, 0.9686274509803922, 0.9803921568627451],
        },
      },
      {
        $extensions: {
          'nl.nldesignsystem.color-scale-position': 3,
          'nl.nldesignsystem.path': 'basis.color.accent-1.bg-default',
          'nl.nldesignsystem.reference-count': 6,
          'nl.nldesignsystem.referenced-at': [
            'basis.color.accent-2.bg-default',
            'basis.color.accent-3.bg-default',
            'basis.color.action-1.bg-default',
            'basis.color.action-2.bg-default',
            'basis.color.selected.bg-default',
            'utrecht.page-footer.background-color',
          ],
          'nl.nldesignsystem.token-subtype': 'background-color',
        },
        $type: 'color',
        $value: {
          alpha: 1,
          colorSpace: 'srgb',
          components: [0.9254901960784314, 0.9450980392156862, 0.9686274509803922],
        },
      },
      {
        $extensions: {
          'nl.nldesignsystem.color-scale-position': 4,
          'nl.nldesignsystem.path': 'basis.color.accent-1.bg-hover',
          'nl.nldesignsystem.reference-count': 5,
          'nl.nldesignsystem.referenced-at': [
            'basis.color.accent-2.bg-hover',
            'basis.color.accent-3.bg-hover',
            'basis.color.action-1.bg-hover',
            'basis.color.action-2.bg-hover',
            'basis.color.selected.bg-hover',
          ],
          'nl.nldesignsystem.token-subtype': 'background-color',
        },
        $type: 'color',
        $value: {
          alpha: 1,
          colorSpace: 'srgb',
          components: [0.8941176470588236, 0.9254901960784314, 0.9568627450980393],
        },
      },
      {
        $extensions: {
          'nl.nldesignsystem.color-scale-position': 5,
          'nl.nldesignsystem.path': 'basis.color.accent-1.bg-active',
          'nl.nldesignsystem.reference-count': 5,
          'nl.nldesignsystem.referenced-at': [
            'basis.color.accent-2.bg-active',
            'basis.color.accent-3.bg-active',
            'basis.color.action-1.bg-active',
            'basis.color.action-2.bg-active',
            'basis.color.selected.bg-active',
          ],
          'nl.nldesignsystem.token-subtype': 'background-color',
        },
        $type: 'color',
        $value: {
          alpha: 1,
          colorSpace: 'srgb',
          components: [0.8666666666666667, 0.9019607843137255, 0.9450980392156862],
        },
      },
      {
        $extensions: {
          'nl.nldesignsystem.color-scale-position': 6,
          'nl.nldesignsystem.path': 'basis.color.accent-1.border-subtle',
          'nl.nldesignsystem.reference-count': 5,
          'nl.nldesignsystem.referenced-at': [
            'basis.color.accent-2.border-subtle',
            'basis.color.accent-3.border-subtle',
            'basis.color.action-1.border-subtle',
            'basis.color.action-2.border-subtle',
            'basis.color.selected.border-subtle',
          ],
          'nl.nldesignsystem.token-subtype': 'border-color',
        },
        $type: 'color',
        $value: {
          alpha: 1,
          colorSpace: 'srgb',
          components: [0.6901960784313725, 0.7764705882352941, 0.8745098039215686],
        },
      },
      {
        $extensions: {
          'nl.nldesignsystem.color-scale-position': 7,
          'nl.nldesignsystem.path': 'basis.color.accent-1.border-default',
          'nl.nldesignsystem.reference-count': 5,
          'nl.nldesignsystem.referenced-at': [
            'basis.color.accent-2.border-default',
            'basis.color.accent-3.border-default',
            'basis.color.action-1.border-default',
            'basis.color.action-2.border-default',
            'basis.color.selected.border-default',
          ],
          'nl.nldesignsystem.token-subtype': 'border-color',
        },
        $type: 'color',
        $value: {
          alpha: 1,
          colorSpace: 'srgb',
          components: [0.3607843137254902, 0.5372549019607843, 0.7450980392156863],
        },
      },
      {
        $extensions: {
          'nl.nldesignsystem.color-scale-position': 8,
          'nl.nldesignsystem.path': 'basis.color.accent-1.border-hover',
          'nl.nldesignsystem.reference-count': 5,
          'nl.nldesignsystem.referenced-at': [
            'basis.color.accent-2.border-hover',
            'basis.color.accent-3.border-hover',
            'basis.color.action-1.border-hover',
            'basis.color.action-2.border-hover',
            'basis.color.selected.border-hover',
          ],
          'nl.nldesignsystem.token-subtype': 'border-color',
        },
        $type: 'color',
        $value: {
          alpha: 1,
          colorSpace: 'srgb',
          components: [0.3058823529411765, 0.4980392156862745, 0.7215686274509804],
        },
      },
      {
        $extensions: {
          'nl.nldesignsystem.color-scale-position': 9,
          'nl.nldesignsystem.path': 'basis.color.accent-1.border-active',
          'nl.nldesignsystem.reference-count': 5,
          'nl.nldesignsystem.referenced-at': [
            'basis.color.accent-2.border-active',
            'basis.color.accent-3.border-active',
            'basis.color.action-1.border-active',
            'basis.color.action-2.border-active',
            'basis.color.selected.border-active',
          ],
          'nl.nldesignsystem.token-subtype': 'border-color',
        },
        $type: 'color',
        $value: {
          alpha: 1,
          colorSpace: 'srgb',
          components: [0.24705882352941178, 0.4549019607843137, 0.6980392156862745],
        },
      },
      {
        $extensions: {
          'nl.nldesignsystem.color-scale-position': 10,
          'nl.nldesignsystem.path': 'basis.color.accent-1.color-subtle',
          'nl.nldesignsystem.reference-count': 5,
          'nl.nldesignsystem.referenced-at': [
            'basis.color.accent-2.color-subtle',
            'basis.color.accent-3.color-subtle',
            'basis.color.action-1.color-subtle',
            'basis.color.action-2.color-subtle',
            'basis.color.selected.color-subtle',
          ],
          'nl.nldesignsystem.token-subtype': 'color',
        },
        $type: 'color',
        $value: {
          alpha: 1,
          colorSpace: 'srgb',
          components: [0.1607843137254902, 0.39215686274509803, 0.6666666666666666],
        },
      },
      {
        $extensions: {
          'nl.nldesignsystem.color-scale-position': 11,
          'nl.nldesignsystem.path': 'basis.color.accent-1.color-default',
          'nl.nldesignsystem.reference-count': 5,
          'nl.nldesignsystem.referenced-at': [
            'basis.color.accent-2.color-default',
            'basis.color.accent-3.color-default',
            'basis.color.action-1.color-default',
            'basis.color.action-2.color-default',
            'basis.color.selected.color-default',
          ],
          'nl.nldesignsystem.token-subtype': 'color',
        },
        $type: 'color',
        $value: {
          alpha: 1,
          colorSpace: 'srgb',
          components: [0.10588235294117647, 0.34901960784313724, 0.6431372549019608],
        },
      },
      {
        $extensions: {
          'nl.nldesignsystem.color-scale-position': 12,
          'nl.nldesignsystem.path': 'basis.color.accent-1.color-hover',
          'nl.nldesignsystem.reference-count': 5,
          'nl.nldesignsystem.referenced-at': [
            'basis.color.accent-2.color-hover',
            'basis.color.accent-3.color-hover',
            'basis.color.action-1.color-hover',
            'basis.color.action-2.color-hover',
            'basis.color.selected.color-hover',
          ],
          'nl.nldesignsystem.token-subtype': 'color',
        },
        $type: 'color',
        $value: {
          alpha: 1,
          colorSpace: 'srgb',
          components: [0.01568627450980392, 0.28627450980392155, 0.6039215686274509],
        },
      },
      {
        $extensions: {
          'nl.nldesignsystem.color-scale-position': 13,
          'nl.nldesignsystem.path': 'basis.color.accent-1.color-active',
          'nl.nldesignsystem.reference-count': 5,
          'nl.nldesignsystem.referenced-at': [
            'basis.color.accent-2.color-active',
            'basis.color.accent-3.color-active',
            'basis.color.action-1.color-active',
            'basis.color.action-2.color-active',
            'basis.color.selected.color-active',
          ],
          'nl.nldesignsystem.token-subtype': 'color',
        },
        $type: 'color',
        $value: {
          alpha: 1,
          colorSpace: 'srgb',
          components: [0, 0.23137254901960785, 0.5058823529411764],
        },
      },
      {
        $extensions: {
          'nl.nldesignsystem.color-scale-position': 14,
          'nl.nldesignsystem.path': 'basis.color.accent-1.color-document',
          'nl.nldesignsystem.reference-count': 6,
          'nl.nldesignsystem.referenced-at': [
            'basis.color.accent-2.color-document',
            'basis.color.accent-3.color-document',
            'basis.color.action-1.color-document',
            'basis.color.action-2.color-document',
            'basis.color.selected.color-document',
            'ams.page-header.brand-name.color',
          ],
          'nl.nldesignsystem.token-subtype': 'color',
        },
        $type: 'color',
        $value: {
          alpha: 1,
          colorSpace: 'srgb',
          components: [0, 0.10588235294117647, 0.23529411764705882],
        },
      },
    ],
  },
];
