import { ColorGroup } from './types';

export const colorGroups: ColorGroup[] = [
  {
    colorEntries: [
      {
        colorKey: 'bg-document',
        displayValue: '#fffcff',
        tokenId: 'basis.color.default.bg-document',
        usage: [
          'basis.form-control.background-color',
          'utrecht.calendar.background-color',
          'utrecht.drawer.background-color',
          'utrecht.document.background-color',
          'utrecht.page-body.background-color',
          'utrecht.page-body.content.background-color',
          'utrecht.root.background-color',
          'utrecht.body.background-color',
          'utrecht.page-header.background-color',
          'todo.drawer.background-color',
          'todo.progress-list.step-marker.not-checked.background-color',
          'ams.dialog.background-color',
          'denhaag.process-steps.step-marker.background-color',
        ],
        usageCount: 13,
      },
      {
        colorKey: 'bg-subtle',
        displayValue: '#faf0ff',
        tokenId: 'basis.color.default.bg-subtle',
        usage: [
          'basis.form-control.read-only.accent-color',
          'basis.form-control.read-only.background-color',
          'utrecht.nav-bar.background-color',
          'utrecht.nav-bar.content.background-color',
        ],
        usageCount: 4,
      },
      {
        colorKey: 'bg-default',
        displayValue: '#f6e6ff',
        tokenId: 'basis.color.default.bg-default',
        usage: [
          'basis.color.disabled.bg-default',
          'utrecht.accordion.button.background-color',
          'utrecht.code.background-color',
          'utrecht.code-block.background-color',
          'utrecht.data-badge.background-color',
          'utrecht.spotlight-section.background-color',
          'utrecht.number-badge.background-color',
          'utrecht.status-badge.background-color',
          'utrecht.status-badge.inactive.background-color',
          'utrecht.form-toggle.thumb.background-color',
          'todo.case-card.archived.background-color',
          'todo.status-badge.background-color',
          'nl.button.default.background-color',
          'nl.code.background-color',
          'nl.code-block.background-color',
          'nl.data-badge.background-color',
          'nl.number-badge.background-color',
          'denhaag.file.left.background-color',
        ],
        usageCount: 18,
      },
      {
        colorKey: 'bg-hover',
        displayValue: '#f1ddff',
        tokenId: 'basis.color.default.bg-hover',
        usage: [
          'basis.form-control.hover.background-color',
          'utrecht.accordion.button.hover.background-color',
          'utrecht.button.hover.background-color',
          'utrecht.pagination.page-link.hover.background-color',
          'utrecht.pagination.relative-link.hover.background-color',
          'todo.case-card.archived.hover.background-color',
          'nl.button.default.hover.background-color',
          'denhaag.action.single.hover.background-color',
          'rhc.navigation-list.item.hover.background-color',
          'lux.login-link.hover.background-color',
        ],
        usageCount: 10,
      },
      {
        colorKey: 'bg-active',
        displayValue: '#edd3ff',
        tokenId: 'basis.color.default.bg-active',
        usage: [
          'basis.form-control.active.background-color',
          'utrecht.accordion.button.active.background-color',
          'utrecht.button.active.background-color',
          'utrecht.button.pressed.background-color',
          'utrecht.pagination.page-link.current.background-color',
          'todo.case-card.archived.active.background-color',
          'todo.case-card.archived.decoration.folder.background-color',
          'todo.case-card.archived.decoration.folder.active.background-color',
          'todo.case-card.archived.decoration.folder.hover.background-color',
          'todo.pagination.page-link.current.background-color',
          'nl.button.default.active.background-color',
          'rhc.navigation-list.item.active.background-color',
          'lux.login-link.active.background-color',
        ],
        usageCount: 13,
      },
      {
        colorKey: 'border-subtle',
        displayValue: '#c9aaf3',
        tokenId: 'basis.color.default.border-subtle',
        usage: [
          'basis.color.disabled.border-subtle',
          'utrecht.accordion.section.border-color',
          'utrecht.accordion.section.hover.border-color',
          'utrecht.drawer.border-color',
          'utrecht.table.header.border-block-end-color',
          'utrecht.table.row.border-block-end-color',
          'todo.drawer.border-color',
          'todo.drawer.header.border-color',
          'todo.drawer.footer.border-color',
          'todo.form-summary.item.border-color',
          'todo.table.footer.border-block-start-color',
          'ams.dialog.border-color',
          'denhaag.description-list.border-color',
          'denhaag.file.border-color',
          'denhaag.tabs.border-color',
          'denhaag.action.border-color',
          'rhc.navigation-list.item.border-color',
        ],
        usageCount: 17,
      },
      {
        colorKey: 'border-default',
        displayValue: '#8460b0',
        tokenId: 'basis.color.default.border-default',
        usage: [
          'basis.form-control.border-color',
          'utrecht.button.border-color',
          'utrecht.spotlight-section.border-color',
          'utrecht.separator.color',
          'todo.progress-list.connector.not-checked.border-color',
          'todo.progress-list.step-marker.not-checked.border-color',
          'nl.button.default.border-color',
          'denhaag.process-steps.step-line.color',
          'denhaag.process-steps.step-marker.border-color',
          'denhaag.process-steps.sub-step-marker.border-color',
          'denhaag.process-steps.sub-step-marker.current.border-color',
          'denhaag.step-marker.connector.default.outline-color',
          'lux.login-link.border-color',
        ],
        usageCount: 13,
      },
      {
        colorKey: 'border-hover',
        displayValue: '#7b50ab',
        tokenId: 'basis.color.default.border-hover',
        usage: [
          'basis.form-control.hover.border-color',
          'utrecht.button.hover.border-color',
          'nl.button.default.hover.border-color',
          'lux.login-link.hover.border-color',
        ],
        usageCount: 4,
      },
      {
        colorKey: 'border-active',
        displayValue: '#663399',
        tokenId: 'basis.color.default.border-active',
        usage: [
          'basis.form-control.active.border-color',
          'basis.form-control.focus.border-color',
          'utrecht.button.active.border-color',
          'utrecht.button.pressed.border-color',
          'nl.button.default.active.border-color',
          'denhaag.tabs.tab-indicator.border-color',
          'lux.login-link.active.border-color',
        ],
        usageCount: 7,
      },
      {
        colorKey: 'color-subtle',
        displayValue: '#552086',
        tokenId: 'basis.color.default.color-subtle',
        usage: [
          'basis.color.disabled.color-subtle',
          'basis.color.disabled.color-default',
          'basis.color.disabled.color-hover',
          'basis.color.disabled.color-active',
          'basis.color.disabled.color-document',
          'basis.form-control.placeholder.color',
          'utrecht.blockquote.attribution.color',
          'utrecht.breadcrumb-nav.separator.color',
          'utrecht.form-field-description.color',
          'todo.breadcrumb-nav.separator.color',
          'todo.pagination.ellipses.color',
          'todo.progress-list.step-heading.not-checked.color',
          'denhaag.process-steps.step-description.color',
          'denhaag.process-steps.step-metaddata.color',
          'rhc.navigation-list.item.description.color',
        ],
        usageCount: 15,
      },
      {
        colorKey: 'color-default',
        displayValue: '#450773',
        tokenId: 'basis.color.default.color-default',
        usage: [
          'utrecht.button.color',
          'utrecht.data-badge.color',
          'utrecht.number-badge.color',
          'utrecht.status-badge.color',
          'utrecht.status-badge.inactive.color',
          'todo.status-badge.color',
          'nl.button.default.color',
          'nl.data-badge.color',
          'nl.number-badge.color',
        ],
        usageCount: 9,
      },
      {
        colorKey: 'color-hover',
        displayValue: '#360061',
        tokenId: 'basis.color.default.color-hover',
        usage: [],
        usageCount: 0,
      },
      {
        colorKey: 'color-active',
        displayValue: '#1a003d',
        tokenId: 'basis.color.default.color-active',
        usage: ['utrecht.button.active.color', 'utrecht.button.pressed.color', 'nl.button.default.active.color'],
        usageCount: 3,
      },
      {
        colorKey: 'color-document',
        displayValue: '#120031',
        tokenId: 'basis.color.default.color-document',
        usage: [
          'basis.form-control.color',
          'basis.form-control.read-only.color',
          'utrecht.blockquote.color',
          'utrecht.blockquote.content.color',
          'utrecht.calendar.navigation.label.color',
          'utrecht.code.color',
          'utrecht.code-block.color',
          'utrecht.drawer.color',
          'utrecht.document.color',
          'utrecht.form-fieldset.legend.color',
          'utrecht.form-fieldset.section.color',
          'utrecht.figure.caption.color',
          'utrecht.form-label.color',
          'utrecht.form-label.checkbox.color',
          'utrecht.form-label.radio.color',
          'utrecht.nav-bar.color',
          'utrecht.nav-bar.content.color',
          'utrecht.spotlight-section.color',
          'utrecht.page-body.color',
          'utrecht.page-body.content.color',
          'utrecht.pagination.page-link.current.color',
          'utrecht.paragraph.color',
          'utrecht.paragraph.lead.color',
          'utrecht.paragraph.small.color',
          'utrecht.pre-heading.color',
          'utrecht.root.color',
          'utrecht.table.caption.color',
          'utrecht.table.footer.color',
          'utrecht.table.header.color',
          'utrecht.unordered-list.marker.color',
          'utrecht.body.color',
          'utrecht.page-header.color',
          'utrecht.page-footer.color',
          'todo.case-card.color',
          'todo.case-card.description.color',
          'todo.case-card.metadata.color',
          'todo.case-card.archived.color',
          'todo.case-card.archived.description.color',
          'todo.case-card.archived.metadata.color',
          'todo.drawer.color',
          'todo.drawer.header.label.color',
          'todo.form-field-label-suffix.color',
          'todo.form-summary.item.color',
          'todo.pagination.description.color',
          'todo.pagination.page-link.current.color',
          'todo.progress-list.button.icon.current.color',
          'todo.progress-list.step-heading.current.color',
          'todo.task-list.color',
          'ams.description-list.color',
          'ams.figure.caption.color',
          'nl.code.color',
          'nl.code-block.color',
          'nl.paragraph.color',
          'denhaag.contact-timeline.step-meta.marker.color',
          'denhaag.description-list.color',
          'denhaag.description-list.title.color',
          'denhaag.process-steps.step-heading.color',
          'denhaag.process-steps.step-heading.checked.color',
          'denhaag.process-steps.step-heading.current.color',
          'denhaag.process-steps.step-heading.warning.color',
          'denhaag.process-steps.step-marker.color',
          'denhaag.process-steps.sub-step-heading.color',
          'denhaag.side-navigation.link.current.color',
          'denhaag.step-marker.default.nested.color',
          'denhaag.tabs.tab.selected.color',
          'denhaag.action.color',
          'denhaag.action.date.color',
        ],
        usageCount: 67,
      },
    ],
    key: 'default',
  },
  {
    colorEntries: [
      {
        colorKey: 'bg-document',
        displayValue: '#fbfcfd',
        tokenId: 'basis.color.accent-1.bg-document',
        usage: [
          'basis.color.accent-2.bg-document',
          'basis.color.accent-3.bg-document',
          'basis.color.action-2.bg-document',
          'basis.color.selected.bg-document',
        ],
        usageCount: 4,
      },
      {
        colorKey: 'bg-subtle',
        displayValue: '#f4f7fa',
        tokenId: 'basis.color.accent-1.bg-subtle',
        usage: [
          'basis.color.accent-2.bg-subtle',
          'basis.color.accent-3.bg-subtle',
          'basis.color.action-2.bg-subtle',
          'basis.color.selected.bg-subtle',
        ],
        usageCount: 4,
      },
      {
        colorKey: 'bg-default',
        displayValue: '#ecf1f7',
        tokenId: 'basis.color.accent-1.bg-default',
        usage: [
          'basis.color.accent-2.bg-default',
          'basis.color.accent-3.bg-default',
          'basis.color.action-2.bg-default',
          'basis.color.selected.bg-default',
          'utrecht.page-footer.background-color',
        ],
        usageCount: 5,
      },
      {
        colorKey: 'bg-hover',
        displayValue: '#e4ecf4',
        tokenId: 'basis.color.accent-1.bg-hover',
        usage: [
          'basis.color.accent-2.bg-hover',
          'basis.color.accent-3.bg-hover',
          'basis.color.action-2.bg-hover',
          'basis.color.selected.bg-hover',
        ],
        usageCount: 4,
      },
      {
        colorKey: 'bg-active',
        displayValue: '#dde6f1',
        tokenId: 'basis.color.accent-1.bg-active',
        usage: [
          'basis.color.accent-2.bg-active',
          'basis.color.accent-3.bg-active',
          'basis.color.action-2.bg-active',
          'basis.color.selected.bg-active',
        ],
        usageCount: 4,
      },
      {
        colorKey: 'border-subtle',
        displayValue: '#b0c6df',
        tokenId: 'basis.color.accent-1.border-subtle',
        usage: [
          'basis.color.accent-2.border-subtle',
          'basis.color.accent-3.border-subtle',
          'basis.color.action-2.border-subtle',
          'basis.color.selected.border-subtle',
        ],
        usageCount: 4,
      },
      {
        colorKey: 'border-default',
        displayValue: '#5c89be',
        tokenId: 'basis.color.accent-1.border-default',
        usage: [
          'basis.color.accent-2.border-default',
          'basis.color.accent-3.border-default',
          'basis.color.action-2.border-default',
          'basis.color.selected.border-default',
        ],
        usageCount: 4,
      },
      {
        colorKey: 'border-hover',
        displayValue: '#4e7fb8',
        tokenId: 'basis.color.accent-1.border-hover',
        usage: [
          'basis.color.accent-2.border-hover',
          'basis.color.accent-3.border-hover',
          'basis.color.action-2.border-hover',
          'basis.color.selected.border-hover',
        ],
        usageCount: 4,
      },
      {
        colorKey: 'border-active',
        displayValue: '#3f74b2',
        tokenId: 'basis.color.accent-1.border-active',
        usage: [
          'basis.color.accent-2.border-active',
          'basis.color.accent-3.border-active',
          'basis.color.action-2.border-active',
          'basis.color.selected.border-active',
        ],
        usageCount: 4,
      },
      {
        colorKey: 'color-subtle',
        displayValue: '#2964aa',
        tokenId: 'basis.color.accent-1.color-subtle',
        usage: [
          'basis.color.accent-2.color-subtle',
          'basis.color.accent-3.color-subtle',
          'basis.color.action-2.color-subtle',
          'basis.color.selected.color-subtle',
        ],
        usageCount: 4,
      },
      {
        colorKey: 'color-default',
        displayValue: '#1b59a4',
        tokenId: 'basis.color.accent-1.color-default',
        usage: [
          'basis.color.accent-2.color-default',
          'basis.color.accent-3.color-default',
          'basis.color.action-2.color-default',
          'basis.color.selected.color-default',
        ],
        usageCount: 4,
      },
      {
        colorKey: 'color-hover',
        displayValue: '#04499a',
        tokenId: 'basis.color.accent-1.color-hover',
        usage: [
          'basis.color.accent-2.color-hover',
          'basis.color.accent-3.color-hover',
          'basis.color.action-2.color-hover',
          'basis.color.selected.color-hover',
        ],
        usageCount: 4,
      },
      {
        colorKey: 'color-active',
        displayValue: '#003b81',
        tokenId: 'basis.color.accent-1.color-active',
        usage: [
          'basis.color.accent-2.color-active',
          'basis.color.accent-3.color-active',
          'basis.color.action-2.color-active',
          'basis.color.selected.color-active',
        ],
        usageCount: 4,
      },
      {
        colorKey: 'color-document',
        displayValue: '#001b3c',
        tokenId: 'basis.color.accent-1.color-document',
        usage: [
          'basis.color.accent-2.color-document',
          'basis.color.accent-3.color-document',
          'basis.color.action-2.color-document',
          'basis.color.selected.color-document',
          'ams.page-header.brand-name.color',
        ],
        usageCount: 5,
      },
    ],
    key: 'accent-1',
  },
];
